name: CodeBuild CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Adjust to your Node.js version

      - name: Install dependencies
        run: |
          npm install
          cd client
          npm install
          cd ..
          cd server
          npm install
          cd ..

      - name: Run front and backend tests
        run: npm test
        env:
          NODE_ENV: test
          AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=terratrove;AccountKey=DJkiS08KgUajs8vQukPuHYn9NPNWy0HpQj9bZnn+9ya0iKBisqidPJVnUpz5KrGhRjMmU33s0xxq+ASt8IqMYw==;EndpointSuffix=core.windows.net"
          
